global:
  scrape_interval: 5s   # Cada 5 segundos Prometheus revisa la aplicacion

scrape_configs:
  - job_name: "orders-app"
    metrics_path: "/actuator/prometheus" 
    static_configs:
      - targets: ["host.docker.internal:8080"]
